# -*- coding: utf-8 -*-
"""patl_rl_extension.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IfFx43kpxRbVrYDTR1gsMyWCDisrNSRw
"""

import pickle
import numpy as np

# Load CT data
with open('ct_scan_pca_5000_vgg16.pickle', 'rb') as f:
    ct_data = pickle.load(f)

# Load X-ray data
with open('x_ray_pca_5000_vgg16.pickle', 'rb') as f:
    xray_data = pickle.load(f)

sample = ct_data[0]

print("Sample keys:", sample.keys())
for key, value in sample.items():
    print(f"{key} → Type: {type(value)}, Shape: {np.array(value).shape if hasattr(value, 'shape') else 'N/A'}")

# Extract features and labels from the list of dicts
X_ct = np.array([sample['image'] for sample in ct_data])
y_ct = np.array([sample['label'] for sample in ct_data])

print("X_ct shape (features):", X_ct.shape)  # Expecting (5000, 5000)
print("y_ct shape (labels):", y_ct.shape)    # Expecting (5000,)
print("Label distribution:", np.unique(y_ct, return_counts=True))

from sklearn.model_selection import train_test_split

# Shuffle and split the dataset into 200 mentored, 50 test, 4750 unlabeled
X_temp, X_test, y_temp, y_test = train_test_split(X_ct, y_ct, test_size=50, stratify=y_ct, random_state=42)
X_mentor, X_unlabeled, y_mentor, y_unlabeled = train_test_split(X_temp, y_temp, test_size=4750, stratify=y_temp, random_state=42)

print("Mentored set:", X_mentor.shape)
print("Test set:", X_test.shape)
print("Unlabeled pool:", X_unlabeled.shape)

!pip install stable-baselines3

import gym
from gym import spaces
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

class SampleSelectionEnv(gym.Env):
    def __init__(self, X_unlabeled, y_unlabeled, X_mentor, y_mentor):
        super(SampleSelectionEnv, self).__init__()
        self.X_unlabeled = X_unlabeled
        self.y_unlabeled = y_unlabeled
        self.X_mentor = X_mentor
        self.y_mentor = y_mentor
        self.current_index = 0
        self.model = LogisticRegression(max_iter=1000)

        # Observation: feature vector
        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(X_unlabeled.shape[1],), dtype=np.float32)

        # Action: 0 = skip, 1 = select
        self.action_space = spaces.Discrete(2)

    def reset(self):
        self.current_index = 0
        self.labeled_X = self.X_mentor.copy()
        self.labeled_y = self.y_mentor.copy()
        return self.X_unlabeled[self.current_index]

    def step(self, action):
        done = False
        reward = 0

        x = self.X_unlabeled[self.current_index]
        y_true = self.y_unlabeled[self.current_index]

        if action == 1:
            # Select the sample: add it to training data
            self.labeled_X = np.vstack([self.labeled_X, x])
            self.labeled_y = np.append(self.labeled_y, y_true)

            # Retrain model and compute reward
            self.model.fit(self.labeled_X, self.labeled_y)
            acc = accuracy_score(self.y_mentor, self.model.predict(self.X_mentor))
            reward = 1 if acc > 0.85 else -1
        else:
            # Skip the sample
            reward = -0.1  # small penalty for not learning

        self.current_index += 1
        if self.current_index >= len(self.X_unlabeled):
            done = True
            obs = self.X_unlabeled[0]  # dummy
        else:
            obs = self.X_unlabeled[self.current_index]

        return obs, reward, done, {}

!pip install "shimmy>=2.0"

from stable_baselines3 import PPO

# Create environment without vectorization
env = SampleSelectionEnv(X_unlabeled, y_unlabeled, X_mentor, y_mentor)

# Train the PPO agent
model = PPO("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=10000)

selected_X = []
selected_y = []

env = SampleSelectionEnv(X_unlabeled, y_unlabeled, X_mentor, y_mentor)
obs = env.reset()

for _ in range(len(X_unlabeled)):
    action, _ = model.predict(obs)
    if action == 1:
        # Select sample and get oracle label
        x = env.X_unlabeled[env.current_index]
        y = env.y_unlabeled[env.current_index]
        selected_X.append(x)
        selected_y.append(y)
    obs, reward, done, _ = env.step(action)
    if done:
        break

print("Number of samples selected by RL agent:", len(selected_X))

X_dagger = np.vstack([X_mentor] + selected_X)
y_dagger = np.hstack([y_mentor] + selected_y)

print("Total samples for imitation learner:", X_dagger.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Train the imitation learner
imitation_model = LogisticRegression(max_iter=1000)
imitation_model.fit(X_dagger, y_dagger)

# Evaluate on test set
y_pred = imitation_model.predict(X_test)
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

from sklearn.model_selection import train_test_split

X_temp, X_test, y_temp, y_test = train_test_split(X_ct, y_ct, test_size=50, stratify=y_ct, random_state=99)

base_model = LogisticRegression(max_iter=1000)
base_model.fit(X_mentor, y_mentor)
y_base_pred = base_model.predict(X_test)

print("Baseline Only (200 Mentored)")
print(classification_report(y_test, y_base_pred))

X_temp, X_test, y_temp, y_test = train_test_split(X_ct, y_ct, test_size=0.20, stratify=y_ct, random_state=42)
# Use 20% = 1000 samples for test

from sklearn.model_selection import train_test_split

# Split 20% of the total data (1000 samples) as test
X_temp, X_test, y_temp, y_test = train_test_split(X_ct, y_ct, test_size=0.20, stratify=y_ct, random_state=99)

# Now split the remaining 4000 into mentored + unlabeled
X_mentor, X_unlabeled, y_mentor, y_unlabeled = train_test_split(X_temp, y_temp, test_size=0.90, stratify=y_temp, random_state=99)

print("Mentored set:", X_mentor.shape)
print("Unlabeled pool:", X_unlabeled.shape)
print("Test set:", X_test.shape)

env = SampleSelectionEnv(X_unlabeled, y_unlabeled, X_mentor, y_mentor)

from stable_baselines3 import PPO
model = PPO("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=10000)

selected_X = []
selected_y = []

env = SampleSelectionEnv(X_unlabeled, y_unlabeled, X_mentor, y_mentor)
obs = env.reset()

for _ in range(len(X_unlabeled)):
    action, _ = model.predict(obs)
    if action == 1:
        x = env.X_unlabeled[env.current_index]
        y = env.y_unlabeled[env.current_index]
        selected_X.append(x)
        selected_y.append(y)
    obs, reward, done, _ = env.step(action)
    if done:
        break

print("Number of samples selected by RL agent:", len(selected_X))

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Combine mentored + RL-selected data
X_dagger = np.vstack([X_mentor] + selected_X)
y_dagger = np.hstack([y_mentor] + selected_y)

# Train imitation model
imitation_model = LogisticRegression(max_iter=1000)
imitation_model.fit(X_dagger, y_dagger)

# Evaluate on test set (1000 samples)
y_pred = imitation_model.predict(X_test)

# Print results
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

# Use all 5000 CT samples (X_ct, y_ct) for this
model = LogisticRegression(max_iter=1000)
scores = cross_val_score(model, X_ct, y_ct, cv=5, scoring='accuracy')

print("5-Fold CV Accuracy Scores:", scores)
print("Mean ± Std:", scores.mean(), "±", scores.std())

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

tsne = TSNE(n_components=2, random_state=42)
X_tsne = tsne.fit_transform(X_ct)

plt.figure(figsize=(10, 6))
plt.scatter(X_tsne[:, 0], X_tsne[:, 1], c=y_ct, cmap='coolwarm', alpha=0.6)
plt.title("t-SNE Visualization of CT PCA Features")
plt.colorbar(label='Class')
plt.xlabel("TSNE-1")
plt.ylabel("TSNE-2")
plt.grid(True)
plt.show()

from sklearn.cluster import KMeans

# Select N samples via K-means from the unlabeled pool
k = 1000  # choose N to match RL's selected count
kmeans = KMeans(n_clusters=k, random_state=42).fit(X_unlabeled)

# Pick 1 sample closest to each cluster center
from scipy.spatial.distance import cdist

selected_idx = []
for center in kmeans.cluster_centers_:
    dists = cdist([center], X_unlabeled)[0]
    idx = dists.argmin()
    selected_idx.append(idx)

# Build new DAgger dataset
X_kmeans = X_unlabeled[selected_idx]
y_kmeans = y_unlabeled[selected_idx]

X_dagger_kmeans = np.vstack([X_mentor, X_kmeans])
y_dagger_kmeans = np.hstack([y_mentor, y_kmeans])

# Train imitation learner
model_kmeans = LogisticRegression(max_iter=1000)
model_kmeans.fit(X_dagger_kmeans, y_dagger_kmeans)
y_pred_kmeans = model_kmeans.predict(X_test)

print("K-means DAgger Results:")
print(classification_report(y_test, y_pred_kmeans))

import numpy as np

def inject_label_noise(y, flip_fraction=0.05, seed=42):
    np.random.seed(seed)
    n = int(len(y) * flip_fraction)
    indices_to_flip = np.random.choice(len(y), size=n, replace=False)
    y_noisy = y.copy()
    y_noisy[indices_to_flip] = 1 - y_noisy[indices_to_flip]  # Binary flip: 0 → 1, 1 → 0
    return y_noisy

# Apply only to mentored labels (simulate noisy oracle)
y_mentor_noisy = inject_label_noise(y_mentor, flip_fraction=0.05)

from sklearn.decomposition import PCA

# Apply PCA to reduce dimensions further
pca = PCA(n_components=200)
X_ct_reduced = pca.fit_transform(X_ct)

# Redo your splits using reduced features
X_temp, X_test, y_temp, y_test = train_test_split(X_ct_reduced, y_ct, test_size=0.20, stratify=y_ct, random_state=42)
X_mentor, X_unlabeled, y_mentor, y_unlabeled = train_test_split(X_temp, y_temp, test_size=0.90, stratify=y_temp, random_state=42)

from sklearn.tree import DecisionTreeClassifier

imitation_model = DecisionTreeClassifier(max_depth=4)  # intentionally shallow

import pickle
import numpy as np

# Load the X-ray PCA features (same structure as CT)
with open('x_ray_pca_5000_vgg16.pickle', 'rb') as f:
    xray_data = pickle.load(f)

# Inspect structure
print(type(xray_data[0]), xray_data[0].keys())

# Extract features and labels from the list of dicts
X_xray = np.array([sample['image'] for sample in xray_data])
y_xray = np.array([sample['label'] for sample in xray_data])

print("X_xray shape:", X_xray.shape)
print("Label distribution:", np.unique(y_xray, return_counts=True))

imitation_model = LogisticRegression(max_iter=1000)
imitation_model.fit(X_dagger, y_dagger)

pca = PCA(n_components=200)
X_ct_reduced = pca.fit_transform(X_ct)

# Convert list to array if it's still a list
selected_X_array = np.array(selected_X)

# Apply the same PCA transform to the selected samples
selected_X_reduced = pca.transform(selected_X_array)

# Now everything matches
X_dagger = np.vstack([X_mentor, selected_X_reduced])
y_dagger = np.hstack([y_mentor, selected_y])

imitation_model = LogisticRegression(max_iter=1000)
imitation_model.fit(X_dagger, y_dagger)

y_pred_xray = imitation_model.predict(X_xray)

X_xray_reduced = pca.transform(X_xray)  # Use the same PCA object
y_pred_xray = imitation_model.predict(X_xray_reduced)

from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Step 1: Evaluate CT-trained imitation model on X-ray data
print("Classification Report (CT → X-ray):")
print(classification_report(y_xray, y_pred_xray))

# Step 2: Plot confusion matrix
conf_matrix = confusion_matrix(y_xray, y_pred_xray)
plt.figure(figsize=(6, 5))
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues", xticklabels=[0,1], yticklabels=[0,1])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix: CT-trained model on X-ray Data")
plt.tight_layout()
plt.show()

# Apply same PCA transform to X-ray data
X_xray_reduced = pca.transform(X_xray)

# Split into test (20%) and the rest
X_temp_xray, X_test_xray, y_temp_xray, y_test_xray = train_test_split(
    X_xray_reduced, y_xray, test_size=0.20, stratify=y_xray, random_state=42)

# From the remaining 80%, take 10% as mentored (400), rest as unlabeled
X_mentor_xray, X_unlabeled_xray, y_mentor_xray, y_unlabeled_xray = train_test_split(
    X_temp_xray, y_temp_xray, test_size=0.90, stratify=y_temp_xray, random_state=42)

# Reuse your SampleSelectionEnv but pass X-ray sets
env_xray = SampleSelectionEnv(X_unlabeled_xray, y_unlabeled_xray, X_mentor_xray, y_mentor_xray)

from stable_baselines3 import PPO

ppo_model_xray = PPO("MlpPolicy", env_xray, verbose=1)
ppo_model_xray.learn(total_timesteps=10000)

selected_X_xray = []
selected_y_xray = []

# Recreate environment to reset internal state
env_xray = SampleSelectionEnv(X_unlabeled_xray, y_unlabeled_xray, X_mentor_xray, y_mentor_xray)
obs = env_xray.reset()

# Let the trained PPO model pick samples
for _ in range(len(X_unlabeled_xray)):
    action, _ = ppo_model_xray.predict(obs)
    if action == 1:
        x = env_xray.X_unlabeled[env_xray.current_index]
        y = env_xray.y_unlabeled[env_xray.current_index]
        selected_X_xray.append(x)
        selected_y_xray.append(y)
    obs, reward, done, _ = env_xray.step(action)
    if done:
        break

print("Number of X-ray samples selected by PPO agent:", len(selected_X_xray))

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Combine mentored + RL-selected data
X_dagger_xray = np.vstack([X_mentor_xray] + selected_X_xray)
y_dagger_xray = np.hstack([y_mentor_xray] + selected_y_xray)

# Train imitation model
imitation_model_xray = LogisticRegression(max_iter=1000)
imitation_model_xray.fit(X_dagger_xray, y_dagger_xray)

# Evaluate on test set
y_pred_xray_final = imitation_model_xray.predict(X_test_xray)

# Print report
print("Classification Report (X-ray PPO + IL):")
print(classification_report(y_test_xray, y_pred_xray_final))

# Confusion matrix
conf_matrix_xray = confusion_matrix(y_test_xray, y_pred_xray_final)
plt.figure(figsize=(6, 5))
sns.heatmap(conf_matrix_xray, annot=True, fmt="d", cmap="Blues", xticklabels=[0,1], yticklabels=[0,1])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix: PPO + IL on X-ray Data")
plt.tight_layout()
plt.show()

from sklearn.cluster import KMeans
from scipy.spatial.distance import cdist

# Use KMeans to select same number of points (≈2922)
k = 2922
kmeans_xray = KMeans(n_clusters=k, random_state=42).fit(X_unlabeled_xray)

# Select one sample per cluster (closest to center)
selected_idx_xray = []
for center in kmeans_xray.cluster_centers_:
    dists = cdist([center], X_unlabeled_xray)[0]
    idx = dists.argmin()
    selected_idx_xray.append(idx)

# Build DAgger set
X_kmeans_xray = X_unlabeled_xray[selected_idx_xray]
y_kmeans_xray = y_unlabeled_xray[selected_idx_xray]

X_dagger_kmeans_xray = np.vstack([X_mentor_xray, X_kmeans_xray])
y_dagger_kmeans_xray = np.hstack([y_mentor_xray, y_kmeans_xray])

# Train imitation model on KMeans-selected data
model_kmeans_xray = LogisticRegression(max_iter=1000)
model_kmeans_xray.fit(X_dagger_kmeans_xray, y_dagger_kmeans_xray)
y_pred_kmeans_xray = model_kmeans_xray.predict(X_test_xray)

# Evaluate
print("KMeans + IL on X-ray:")
print(classification_report(y_test_xray, y_pred_kmeans_xray))

conf_matrix_kmeans_xray = confusion_matrix(y_test_xray, y_pred_kmeans_xray)
plt.figure(figsize=(6, 5))
sns.heatmap(conf_matrix_kmeans_xray, annot=True, fmt="d", cmap="Blues", xticklabels=[0,1], yticklabels=[0,1])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix: KMeans + IL on X-ray Data")
plt.tight_layout()
plt.show()

import zipfile
import os

zip_path = "/content/COVID_19_Radiography_Dataset_Unseen.zip"
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content/")

import os
import cv2
import numpy as np
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from tensorflow.keras.models import Model

# Load VGG16 without top layer
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
model = Model(inputs=base_model.input, outputs=base_model.output)

# Path to unseen dataset folders
base_path = "/content/COVID_19_Radiography_Dataset_Unseen"
classes = ["COVID", "Normal", "Viral Pneumonia"]
label_map = {"COVID": 0, "Normal": 1, "Viral Pneumonia": 2}  # adjust if needed

X_unseen_raw = []
y_unseen_raw = []

# Loop through each class folder
for cls in classes:
    folder = os.path.join(base_path, cls, "images")
    for file in os.listdir(folder):
        if file.lower().endswith(".png"):
            path = os.path.join(folder, file)
            img = cv2.imread(path)
            img = cv2.resize(img, (224, 224))
            img = preprocess_input(img.astype(np.float32))
            X_unseen_raw.append(img)
            y_unseen_raw.append(label_map[cls])

X_unseen_raw = np.array(X_unseen_raw)
y_unseen_raw = np.array(y_unseen_raw)

# Feature extraction with VGG16
features_unseen = model.predict(X_unseen_raw, batch_size=32)
features_unseen_flat = features_unseen.reshape((features_unseen.shape[0], -1))

# Apply same PCA transform
X_unseen_pca = pca.transform(features_unseen_flat)

# Predict using trained imitation model
y_unseen_pred = imitation_model_xray.predict(X_unseen_pca)

# Report
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

print("Evaluation on Unseen X-ray:")
print(classification_report(y_unseen_raw, y_unseen_pred))

conf = confusion_matrix(y_unseen_raw, y_unseen_pred)
plt.figure(figsize=(6,5))
sns.heatmap(conf, annot=True, fmt='d', cmap='Blues', xticklabels=classes, yticklabels=classes)
plt.title("Confusion Matrix: PPO + IL on X-ray Unseen Set")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.tight_layout()
plt.show()

